/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Object1 {
  f1: string
}
export declare function createObject1(): Object1
export declare function setObject1(val: Object1): void
export interface Object2 {
  f1: string
  f2: string
}
export declare function createObject2(): Object2
export declare function setObject2(val: Object2): void
export interface Object3 {
  f1: string
  f2: string
  f3: string
}
export declare function createObject3(): Object3
export declare function setObject3(val: Object3): void
export interface Object4 {
  f1: string
  f2: string
  f3: string
  f4: string
}
export declare function createObject4(): Object4
export declare function setObject4(val: Object4): void
export interface Object5 {
  f1: string
  f2: string
  f3: string
  f4: string
  f5: string
}
export declare function createObject5(): Object5
export declare function setObject5(val: Object5): void
export interface Object6 {
  f1: string
  f2: string
  f3: string
  f4: string
  f5: string
  f6: string
}
export declare function createObject6(): Object6
export declare function setObject6(val: Object6): void
export interface Object7 {
  f1: string
  f2: string
  f3: string
  f4: string
  f5: string
  f6: string
  f7: string
}
export declare function createObject7(): Object7
export declare function setObject7(val: Object7): void
export interface Object8 {
  f1: string
  f2: string
  f3: string
  f4: string
  f5: string
  f6: string
  f7: string
  f8: string
}
export declare function createObject8(): Object8
export declare function setObject8(val: Object8): void
export interface Object9 {
  f1: string
  f2: string
  f3: string
  f4: string
  f5: string
  f6: string
  f7: string
  f8: string
  f9: string
}
export declare function createObject9(): Object9
export declare function setObject9(val: Object9): void
export interface Object10 {
  f1: string
  f2: string
  f3: string
  f4: string
  f5: string
  f6: string
  f7: string
  f8: string
  f9: string
  f10: string
}
export declare function createObject10(): Object10
export declare function setObject10(val: Object10): void
export declare function createClass1(): Class1
export declare function setClass1(val: Class1): void
export declare function createClass2(): Class2
export declare function setClass2(val: Class2): void
export declare function createClass3(): Class3
export declare function setClass3(val: Class3): void
export declare function createClass4(): Class4
export declare function setClass4(val: Class4): void
export declare function createClass5(): Class5
export declare function setClass5(val: Class5): void
export declare function createClass6(): Class6
export declare function setClass6(val: Class6): void
export declare function createClass7(): Class7
export declare function setClass7(val: Class7): void
export declare function createClass8(): Class8
export declare function setClass8(val: Class8): void
export declare function createClass9(): Class9
export declare function setClass9(val: Class9): void
export declare function createClass10(): Class10
export declare function setClass10(val: Class10): void
export declare class Class1 {
  get f1(): string
}
export declare class Class2 {
  get f1(): string
  get f2(): string
}
export declare class Class3 {
  get f1(): string
  get f2(): string
  get f3(): string
}
export declare class Class4 {
  get f1(): string
  get f2(): string
  get f3(): string
  get f4(): string
}
export declare class Class5 {
  get f1(): string
  get f2(): string
  get f3(): string
  get f4(): string
  get f5(): string
}
export declare class Class6 {
  get f1(): string
  get f2(): string
  get f3(): string
  get f4(): string
  get f5(): string
  get f6(): string
}
export declare class Class7 {
  get f1(): string
  get f2(): string
  get f3(): string
  get f4(): string
  get f5(): string
  get f6(): string
  get f7(): string
}
export declare class Class8 {
  get f1(): string
  get f2(): string
  get f3(): string
  get f4(): string
  get f5(): string
  get f6(): string
  get f7(): string
  get f8(): string
}
export declare class Class9 {
  get f1(): string
  get f2(): string
  get f3(): string
  get f4(): string
  get f5(): string
  get f6(): string
  get f7(): string
  get f8(): string
  get f9(): string
}
export declare class Class10 {
  get f1(): string
  get f2(): string
  get f3(): string
  get f4(): string
  get f5(): string
  get f6(): string
  get f7(): string
  get f8(): string
  get f9(): string
  get f10(): string
}
