/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Object1 {
  f1: string
}
export declare function createObject1(): Object1
export declare function setObject1(val: Object1): void
export interface Object2 {
  f1: string
  f2: string
}
export declare function createObject2(): Object2
export declare function setObject2(val: Object2): void
export interface Object3 {
  f1: string
  f2: string
  f3: string
}
export declare function createObject3(): Object3
export declare function setObject3(val: Object3): void
export interface Object4 {
  f1: string
  f2: string
  f3: string
  f4: string
}
export declare function createObject4(): Object4
export declare function setObject4(val: Object4): void
export declare function createClass1(): Class1
export declare function setClass1(val: Class1): void
export declare function createClass2(): Class2
export declare function setClass2(val: Class2): void
export declare function createClass3(): Class3
export declare function setClass3(val: Class3): void
export declare function createClass4(): Class4
export declare function setClass4(val: Class4): void
export declare class Class1 {
  get f1(): string
}
export declare class Class2 {
  get f1(): string
  get f2(): string
}
export declare class Class3 {
  get f1(): string
  get f2(): string
  get f3(): string
}
export declare class Class4 {
  get f1(): string
  get f2(): string
  get f3(): string
  get f4(): string
}
